### ISSUE TITLE
Quiz/project Feedback

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/programming-in-python-for-data-science#56]
Hi @mgelbart 

Can you please take a look at the quizzes located [here](https://canvas.ubc.ca/courses/67575/assignments) named Quiz1 and Quiz 2? 
If you think any are too hard or not great, let us know and we can make some adjustments. 

If you like, you could also peek at the project instructions and rubric.

**Comment by mgelbart** [comment]
## Quiz 1

Should we consider migrating this to the "new quiz" platform? This looks like an "old quiz". I forgot the pros/cons. Is this fully autograded? Let's discuss this before any action is taken.

- Q1: why not make this a multiple answers with 3 answers. Also for answer 3, the "not" makes things more confusing. How about "They can be stored in a .csv file" and have that one be true as well? I think, in general, I would do this for all the "multiple answer" questions to make them less confusing.
- Q2: df.loc should be in code font. ;; df.iloc should have square brackets.
- Q3: I find the extra whitespace confusing in code font, let's remove, e.g. `df. sort _` -> `df.sort_`
- Q5: It's a bit confusing that two types of quotation marks are used in the same question. Let's standardize everything on whatever we use in the lessons.
- Q7: the chaining one is a bit ambiguous because who knows what it does under the hood. How about "chaining avoids the needs to store intermediate objects". 
- Q9: the NOT + multiple answers is really confusing. Is this meant to be multiple choice?
- Q12: maybe built-in python data types, just to be safe
- Q17: maybe add "with pandas" because read.csv is correct in R?

I think the length and difficulty make sense. Do they get a grade at the end or is it pass fail or...?

**Comment by mgelbart** [comment]
## Quiz 2

- Q2: it's -> its ;; formatting issue in the last answer ;; make clear in the question text that it's "select all that apply"
- Q3: was -> were;; this one is a bit tricky, how about adding another question with `d = double_it(d)` to draw their attention to the "trick"
- Q4: too tricky/strange. Answer 2 is strange. Also there's no mention of the big flaw that it only works for lists of length 4. Also `list` _is_ a reserved keyword, but it technically works, but we shouldn't set a bad example of doing this.
- Q5: dry -> DRY
- Q6: gets -> get;; also they can just try this out so I'm not sure ;; also I would have expected the answer to be 40, what am I missing? OH it asks about the OUTER loop, ok this is too confusing/tricky. Delete?
- Q7: use proper whitespace, `<0` should be `< 0` I think? ;; what is up with the `mean` at the bottom, is that a mistake? Or should it be np.mean? I don't think there's a `mean` built in to Python? Change to `sum`? 
- Q8: again, let's skip the funky answers. Also, the first answer is technically true. Maybe change to have a blank docstring and ask them to fill in pieces or something?
- Q9: too easy?
- Q10: did we cover this? Even if so, let's change the question to something more core/central to the course.
- Q14: time interval between
- Q15: a bit tricky but OK
- Q16: how do we know what goes in the first box?

I think this one needs a bit more work than Quiz 1. Happy to discuss more in a meeting as well.
